// <auto-generated />
namespace E_Trade.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SpecName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpecName));
        
        string IMigrationMetadata.Id
        {
            get { return "202104251016474_SpecName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
